apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $NAME
  region: $AWS_REGION

vpc:
  subnets:
    private:
      $AWS_PRI_AZ_A: { id: $AWS_PRI_SB_A }
      $AWS_PRI_AZ_B: { id: $AWS_PRI_SB_B }
      $AWS_PRI_AZ_C: { id: $AWS_PRI_SB_C }
    public:
      $AWS_PUB_AZ_A: { id: $AWS_PUB_SB_A }
      $AWS_PUB_AZ_B: { id: $AWS_PUB_SB_B }
      $AWS_PUB_AZ_C: { id: $AWS_PUB_SB_C }

nodeGroups:
  - name: $NAME
    minSize: 0
    maxSize: 10
    desiredCapacity: 2
    volumeSize: 60
    privateNetworking: true
    ssh:
      allow: true
    instancesDistribution:
      instanceTypes: ["r5a.large", "m5a.large"]
      onDemandPercentageAboveBaseCapacity: 25
    iam:
      withAddonPolicies:
        autoScaler: true

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]