apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $NAME
  region: $AWS_REGION
  version: "$KUBE_VER"

nodeGroups:
  - name: $NAME
    minSize: $NODE_MIN
    maxSize: $NODE_MAX
    desiredCapacity: 1
    volumeSize: 60
    privateNetworking: true
    instancesDistribution:
      instanceTypes: $NODE_TYPE
      onDemandPercentageAboveBaseCapacity: 25
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true

availabilityZones: $AWS_ZONES

cloudWatch:
  clusterLogging:
    enableTypes: ["audit", "authenticator", "controllerManager"]